default: &default
  adapter: postgresql
  encoding: unicode
  user: lucasrusso
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: OneBitFood_development

test:
  <<: *default
  database: OneBitFood_test

production:
  <<: *default
  database: OneBitFood_production
  username: OneBitFood
  password: <%= ENV['ONEBITFOOD_DATABASE_PASSWORD'] %>
